// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghurjtyemwqbwscjyppv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodXJqdHllbXdxYndzY2p5cHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTA2MDUsImV4cCI6MjA1ODk4NjYwNX0.yu5uaxEPmdco5I0g49DAy_sEFATDyXUSm8bj6fjU7tA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);